### ISSUE TITLE
App failed to run on Android

### ISSUE THREAD

**Issue by RegNex** [RegNex/Tasky-Mobile-App#3]
**Describe the bug**
App not running 

**Additional context**
```
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[+1097 ms] > Task :app:processDebugResources FAILED
[        ] 187 actionable tasks: 5 executed, 182 up-to-date
[   +1 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]      /Users/etornam/Projects/FlutterProjects/tasky_app/android/app/src/main/res/drawable/launch_background.xml:8: AAPT: error: 'tasky_logo.png' is
incompatible with attribute src (attr) reference|color.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 11s
[ +491 ms] Running Gradle task 'assembleDebug'... (completed in 12.5s)
[   +1 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +4 ms] Building plugin apple_sign_in...
[   +3 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /Users/etornam/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/android/gradlew.
[        ] /Users/etornam/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/etornam/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/android/]
/Users/etornam/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/android/gradlew
-I=/Users/etornam/Development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/etornam/Development/flutter
-Poutput-dir=/Users/etornam/Projects/FlutterProjects/tasky_app/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+1246 ms] 
                    > Configure project :
                    WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
                    The current default is 'false'
                    Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.


                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project 'apple_sign_in'.
                    > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
                    full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 1s
[        ] Running Gradle task 'assembleAarRelease'... (completed in 1.2s)
[        ] 
           > Configure project :
           WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
           The current default is 'false'
           Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.
           
[        ] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'apple_sign_in'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 1s
           
[ +191 ms] Exception: The plugin apple_sign_in could not be built due to the issue above.
[   +1 ms] "flutter run" took 19,778ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +128 ms] ensureAnalyticsSent: 127ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by RegNex** [comment]
fixed
